package com.captrojo.complexhud.api;

public enum PositionOrigin
{
	TOP_LEFT,
	TOP_CENTER,
	TOP_RIGHT,
	MIDDLE_LEFT,
	MIDDLE_CENTER,
	MIDDLE_RIGHT,
	BOTTOM_LEFT,
	BOTTOM_CENTER,
	BOTTOM_RIGHT,
	HOTBAR_TOP_LEFT,
	HOTBAR_TOP_RIGHT,
	HOTBAR_SIDE_LEFT,
	HOTBAR_SIDE_RIGHT;
}
